ruby_framework_for_db_backend/config/routes.rb
Forensics::Application.routes.draw do
  resources :loci_groups

  resources :strs

  resources :snps

  resources :experimenters

  root "experiments#index"

  resources :loci

  resources :panel_loci

  resources :ethnicities

  resources :ancestries do
    collection do
      get :map
    end
  end

  resources :calls

  resources :primers

  resources :geographics

  resources :frequencies

  resources :locus_attributes

  resources :attachments do
    member do
      get :download
      post :upload
    end
  end

  resources :attachments

  resources :folders

  resources :panels

  resources :images do
    member do
      get :download
      get :show_img
      post :upload
    end # do
  end # images

  resources :points

  resources :kinships

  resources :relationships

  resources :allele_references

  resources :barcodes

  resources :comparisons

  resources :experiments do
    member do
      post 'form_action'
      get 'graph_best'
    end
  end

  resources :parameters

  resources :samples do
    collection do
      post 'form_action'
    end
  end

  resources :instruments

  resources :families

  resources :people

  resources :person_values

  resources :choices

  resources :attributes

  resources :logins do
    collection do
      get 'logout', 'logins'
      post 'verify'
    end # do
  end # do

end

ruby_framework_for_db_backend/app/models/attachment.rb
class Attachment < ActiveRecord::Base
  has_and_belongs_to_many :parameters
  has_many :experiment
  has_many :panel
  belongs_to :user
  belongs_to :folder

  validates :file_name, uniqueness: true

  scope :has_content, lambda { where("attachments.content_type is NOT NULL") }

  def datafile=(input_data)
    self.file_name = input_data.original_filename
    self.content_type = input_data.content_type.chomp
    self.contents = input_data.read
    self.content_bytes = self.contents.size
  end


  def self.panel_datafile(input_data, description, panel_type)
    return nil if input_data == '' || input_data.nil? #no file name was entered
    attachment = Attachment.new
    attachment.user_id = User.find_by_name('SYSTEM').id
    attachment.folder_id = Folder.find_by_name('Panel Data').id
    attachment.file_name = input_data.original_filename
    attachment.description = description
    attachment.file_type = panel_type
    attachment.content_type = input_data.content_type.chomp
    attachment.contents = input_data.read
    attachment.content_bytes = attachment.contents.size
    attachment.save
    attachment.id
  end

  # datafile

  def self.grab_shortinfo(folder_id)
    sql_cmd = "SELECT id, file_name from attachments where folder_id=#{folder_id}"
    info = Attachment.find_by_sql(sql_cmd)
    info
  end
end # Attachment

ruby_framework_for_db_backend/app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy, :download]

  # GET /attachments
  # GET /attachments.json
  def index
    if params[:folder_id]
      @attachments = Folder.find(params[:folder_id]).attachments
    else
      @attachments = Attachment.all
    end
    @users_hash = Tools::to_hash(User.all)
    @folders_hash = Tools::to_hash(Folder.all)
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @folder = Folder.find_by_id(params[:folder_id]) if params[:folder_id]
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    user_folder = Folder.find(User.find(session[:user_id]).home_folder_id)

    respond_to do |format|
      if @attachment.update(user_id: session[:user_id], folder_id: user_folder.id, file_type: 'User Uploaded Data')
        format.html { redirect_to attachments_path, notice: 'Attachment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attachment }
      else
        format.html { render action: 'new' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.json { head :no_content }
    end
  end

  #############################################################################
  def download
    send_data(@attachment.contents, filename: @attachment.file_name, type: @attachment.content_type)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_attachment
    @attachment = Attachment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attachment_params
    params.require(:attachment).permit(:user_id, :folder_id, :file_name, :description, :file_type,
                                       :content_type, :updated_at, :contents_bytes, :contents, :is_parsed, :datafile)
  end


#############################################################################


end

ruby_framework_for_db_backend/app/helpers/attachments_helper.rb
module AttachmentsHelper
  def map_params(description)
    #gets a lookup array from Ancestries, in the form of an Array of tuples, [source_description, person_sample_id]
    lookup_array = Ancestry.uniq.pluck(:source_description, :person_sample_id)
    #makes the lookup_array into a hash for ease of use
    lookup_hash = Hash[ lookup_array ]


    description_lines = description.split(/\n/)
    target_person_sample_ids=[]
    description_lines.each do |line|
      target_person_sample_ids << lookup_hash[line] unless lookup_hash[line].nil?
    end
    target_person_sample_ids
  end
end

ruby_framework_for_db_backend/app/views/attachments/_form.html.erb
<%= render(partial: 'layouts/error_messages', locals: {object: @attachment}) %>

<%= form_for(@attachment, :html => {:multipart => true}) do |f| %>
    <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
    </div>

    <% if @attachment.new_record? %>
        <div class="field">
            <%= f.label :file %><br>
            <%= f.file_field("datafile") %><br>
            <label>Max file size is 100 megabytes for files.</label>
        </div>
    <% end %>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

ruby_framework_for_db_backend/app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

ruby_framework_for_db_backend/app/views/attachments/index.html.erb
<h1>Files<%= " for folder: #{@folder.name}" if @folder %></h1>

<table class="display dataTable" cellspacing="0" width="100%">

    <thead>
    <tr>
        <th>User</th>
        <th>Folder</th>
        <th>Description</th>
        <th>File type</th>
        <th>Updated at</th>
        <th>Download</th>
    </tr>
    </thead>

    <tbody>
    <% @attachments.each do |attachment| %>
        <tr>
            <td><%= attachment.user_id ? @users_hash[attachment.user_id].name : "System" %></td>
            <td><%= link_to(@folders_hash[attachment.folder_id].name, folder_path(attachment.folder_id)) if attachment.folder_id %></td>
            <% if attachment.file_type == 'Ancestry' && attachment.user_id != 1 %>
                <td><%= link_to(simple_format(word_wrap(attachment.description)),
                                map_ancestries_path(attachment_id: attachment.id, successes: map_params(attachment.description))) %></td>
            <% else %>
                <td class="swap">
                    <%= content_tag :div,
                                    attachment.description.gsub("\n", '<br>').html_safe,
                                    {data: {textorig: attachment.description.gsub("\n", '<br>')}} if attachment.description %></td>
            <% end %>
            <td><%= attachment.file_type %></td>
            <td><%= local_time(attachment.updated_at, format: "%Y-%m-%d %H:%M") %></td>
            <td><%= link_to('Download', download_attachment_path(attachment.id)) %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'Upload New File to Your Home Folder', new_attachment_path %>

ruby_framework_for_db_backend/app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

ruby_framework_for_db_backend/app/views/attachments/show.html.erb
<% if @attachment.user %>
<p>
    <strong>User:</strong>
    <%= @attachment.user.name %>
</p>
<% end %>

<p>
    <strong>Folder:</strong>
    <%= @attachment.folder.name if @attachment.folder %>
</p>

<p>
    <strong>File name:</strong>
    <%= @attachment.file_name %>
</p>

<p>
    <strong>Description:</strong>
    <%= simple_format(word_wrap(@attachment.description)) %>
</p>

<p>
    <strong>File type:</strong>
    <%= @attachment.file_type %>
</p>

<p>
    <strong>Updated at:</strong>
    <%= local_time(@attachment.updated_at, format: "%Y-%m-%d %l:%M%P") %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>