ruby_framework_for_db_backend/config/routes.rb
Forensics::Application.routes.draw do
  resources :loci_groups

  resources :strs

  resources :snps

  resources :experimenters

  root "experiments#index"

  resources :loci

  resources :panel_loci

  resources :ethnicities

  resources :ancestries do
    collection do
      get :map
    end
  end

  resources :calls

  resources :primers

  resources :geographics

  resources :frequencies

  resources :locus_attributes

  resources :attachments do
    member do
      get :download
      post :upload
    end
  end

  resources :attachments

  resources :folders

  resources :panels

  resources :images do
    member do
      get :download
      get :show_img
      post :upload
    end # do
  end # images

  resources :points

  resources :kinships

  resources :relationships

  resources :allele_references

  resources :barcodes

  resources :comparisons

  resources :experiments do
    member do
      post 'form_action'
      get 'graph_best'
    end
  end

  resources :parameters

  resources :samples do
    collection do
      post 'form_action'
    end
  end

  resources :instruments

  resources :families

  resources :people

  resources :person_values

  resources :choices

  resources :attributes

  resources :logins do
    collection do
      get 'logout', 'logins'
      post 'verify'
    end # do
  end # do

end

ruby_framework_for_db_backend/app/models/family.rb
class Family < ActiveRecord::Base
end

ruby_framework_for_db_backend/app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render action: 'show', status: :created, location: @family }
      else
        format.html { render action: 'new' }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_family
    @family = Family.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def family_params
    params.require(:family).permit(:name, :source)
  end
end

ruby_framework_for_db_backend/app/helpers/families_helper.rb
module FamiliesHelper
end

ruby_framework_for_db_backend/app/views/families/_form.html.erb
<%= render(partial: 'layouts/error_messages', locals: {object: @family}) %>

<%= form_for(@family) do |f| %>

    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :source %><br>
        <%= f.text_field :source %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

ruby_framework_for_db_backend/app/views/families/edit.html.erb
<h1>Editing family</h1>

<%= render 'form' %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

ruby_framework_for_db_backend/app/views/families/index.html.erb
<h1>Families</h1>

<table class="display dataTable" cellspacing="0" width="100%">

    <thead>
    <tr>
        <th>Name</th>
        <th>Source</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    <% @families.each do |family| %>
        <tr>
            <td><%= family.name %></td>
            <td><%= family.source %></td>
            <td><%= link_to 'Show', family %></td>
            <td><%= link_to 'Edit', edit_family_path(family) %></td>
            <td><%= link_to 'Destroy', family, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Family', new_family_path %>

ruby_framework_for_db_backend/app/views/families/new.html.erb
<h1>New family</h1>

<%= render 'form' %>

<%= link_to 'Back', families_path %>

ruby_framework_for_db_backend/app/views/families/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @family.name %>
</p>

<p>
    <strong>Source:</strong>
    <%= @family.source %>
</p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>