ruby_framework_for_db_backend/config/routes.rb
Forensics::Application.routes.draw do
  resources :loci_groups

  resources :strs

  resources :snps

  resources :experimenters

  root "experiments#index"

  resources :loci

  resources :panel_loci

  resources :ethnicities

  resources :ancestries do
    collection do
      get :map
    end
  end

  resources :calls

  resources :primers

  resources :geographics

  resources :frequencies

  resources :locus_attributes

  resources :attachments do
    member do
      get :download
      post :upload
    end
  end

  resources :attachments

  resources :folders

  resources :panels

  resources :images do
    member do
      get :download
      get :show_img
      post :upload
    end # do
  end # images

  resources :points

  resources :kinships

  resources :relationships

  resources :allele_references

  resources :barcodes

  resources :comparisons

  resources :experiments do
    member do
      post 'form_action'
      get 'graph_best'
    end
  end

  resources :parameters

  resources :samples do
    collection do
      post 'form_action'
    end
  end

  resources :instruments

  resources :families

  resources :people

  resources :person_values

  resources :choices

  resources :attributes

  resources :logins do
    collection do
      get 'logout', 'logins'
      post 'verify'
    end # do
  end # do

end

ruby_framework_for_db_backend/app/models/locus_attribute.rb
class LocusAttribute < ActiveRecord::Base
end

ruby_framework_for_db_backend/app/controllers/locus_attributes_controller.rb
class LocusAttributesController < ApplicationController
  before_action :set_locus_attribute, only: [:show, :edit, :update, :destroy]

  # GET /locus_attributes
  # GET /locus_attributes.json
  def index
    @locus_attributes = LocusAttribute.all
  end

  # GET /locus_attributes/1
  # GET /locus_attributes/1.json
  def show
  end

  # GET /locus_attributes/new
  def new
    @locus_attribute = LocusAttribute.new
  end

  # GET /locus_attributes/1/edit
  def edit
  end

  # POST /locus_attributes
  # POST /locus_attributes.json
  def create
    @locus_attribute = LocusAttribute.new(locus_attribute_params)

    respond_to do |format|
      if @locus_attribute.save
        format.html { redirect_to @locus_attribute, notice: 'Locus attribute was successfully created.' }
        format.json { render action: 'show', status: :created, location: @locus_attribute }
      else
        format.html { render action: 'new' }
        format.json { render json: @locus_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locus_attributes/1
  # PATCH/PUT /locus_attributes/1.json
  def update
    respond_to do |format|
      if @locus_attribute.update(locus_attribute_params)
        format.html { redirect_to @locus_attribute, notice: 'Locus attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @locus_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locus_attributes/1
  # DELETE /locus_attributes/1.json
  def destroy
    @locus_attribute.destroy
    respond_to do |format|
      format.html { redirect_to locus_attributes_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_locus_attribute
    @locus_attribute = LocusAttribute.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def locus_attribute_params
    params.require(:locus_attribute).permit(:locus_id, :attribute_name, :attribute_choice)
  end
end

ruby_framework_for_db_backend/app/helpers/locus_attributes_helper.rb
module LocusAttributesHelper
end

ruby_framework_for_db_backend/app/views/locus_attributes/_form.html.erb
<%= render(partial: 'layouts/error_messages', locals: {object: @locus_attribute}) %>

<%= form_for(@locus_attribute) do |f| %>

    <div class="field">
        <%= f.label :locus_id %><br>
        <%= f.number_field :locus_id %>
    </div>
    <div class="field">
        <%= f.label :attribute_name %><br>
        <%= f.text_field :attribute_name %>
    </div>
    <div class="field">
        <%= f.label :attribute_choice %><br>
        <%= f.text_field :attribute_choice %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

ruby_framework_for_db_backend/app/views/locus_attributes/edit.html.erb
<h1>Editing locus_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @locus_attribute %> |
<%= link_to 'Back', locus_attributes_path %>

ruby_framework_for_db_backend/app/views/locus_attributes/index.html.erb
<h1>Locus Attributes</h1>

<table class="display dataTable" cellspacing="0" width="100%">

    <thead>
    <tr>
        <th>Locus</th>
        <th>Attribute name</th>
        <th>Attribute choice</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    <% @locus_attributes.each do |locus_attribute| %>
        <tr>
            <td><%= locus_attribute.locus_id %></td>
            <td><%= locus_attribute.attribute_name %></td>
            <td><%= locus_attribute.attribute_choice %></td>
            <td><%= link_to 'Show', locus_attribute %></td>
            <td><%= link_to 'Edit', edit_locus_attribute_path(locus_attribute) %></td>
            <td><%= link_to 'Destroy', locus_attribute, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Locus attribute', new_locus_attribute_path %>

ruby_framework_for_db_backend/app/views/locus_attributes/new.html.erb
<h1>New locus_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', locus_attributes_path %>

ruby_framework_for_db_backend/app/views/locus_attributes/show.html.erb
<p>
    <strong>Locus:</strong>
    <%= @locus_attribute.locus_id %>
</p>

<p>
    <strong>Attribute name:</strong>
    <%= @locus_attribute.attribute_name %>
</p>

<p>
    <strong>Attribute choice:</strong>
    <%= @locus_attribute.attribute_choice %>
</p>

<%= link_to 'Edit', edit_locus_attribute_path(@locus_attribute) %> |
<%= link_to 'Back', locus_attributes_path %>